### ISSUE TITLE
Provide references to any similar games

### ISSUE THREAD

**Issue by ugurdogrusoz** [DjCedrics/cs319_group19_project#1]
Any games you're inspired by? If so, please provide references to them. Otherwise, please provide more detail in your project description (README).

**Comment by ugurdogrusoz** [comment]
Looks like you guys addressed this issue. You should have said so (in a comment like this), and assigned it back to me (the creator of the issue) to verify and close it!

**Comment by firat-sivrikaya** [comment]
The issue has been fixed.
