### ISSUE TITLE
Analysis report part 1 feedback

### ISSUE THREAD

**Issue by ugurdogrusoz** [DjCedrics/cs319_group19_project#2]
Overall you've done a good job with the requirements and exact functionality expected from this game. However, your UC model is pretty weak (see attached for details).
[19.analysis.1.pdf](https://github.com/DjCedrics/cs319_group19_project/files/538368/19.analysis.1.pdf)

**Comment by firat-sivrikaya** [comment]
All images are designed by me. No citation is needed.
