### ISSUE TITLE
Please rename repo

### ISSUE THREAD

**Issue by ugurdogrusoz** [DjCedrics/cs319_group19_project#3]
As 2X.\<project name\>

**Comment by ugurdogrusoz** [comment]
where 2X is your group number :)

**Comment by cgdsyilmaz** [comment]
hocam, we took this course one year ago, so should we write our group number then?

**Comment by ugurdogrusoz** [comment]
Arent you taking it this semester? If so, look up the Groups sheet in course page and use 2A, 2B or whatever for repo name. There is no group 2X.

**Comment by cihangir-mercan** [comment]
No, we took it in Fall 2016.

**Comment by ugurdogrusoz** [comment]
Never mind, my mistake
